// Menu Mobile
document.addEventListener('DOMContentLoaded', function() {
    const mobileMenu = document.querySelector('.mobile-menu');
        const nav = document.querySelector('nav');
            
                mobileMenu.addEventListener('click', function() {
                        nav.classList.toggle('active');
                            });
                                
                                    // Fechar menu ao clicar em um link
                                        const navLinks = document.querySelectorAll('nav ul li a');
                                            navLinks.forEach(link => {
                                                    link.addEventListener('click', function() {
                                                                nav.classList.remove('active');
                                                                        });
                                                                            });
                                                                                
                                                                                    // Form de contato
                                                                                        const contactForm = document.getElementById('contactForm');
                                                                                            if (contactForm) {
                                                                                                    contactForm.addEventListener('submit', function(e) {
                                                                                                                e.preventDefault();
                                                                                                                            
                                                                                                                                        // Simulação de envio
                                                                                                                                                    const formData = new FormData(contactForm);
                                                                                                                                                                const formValues = Object.fromEntries(formData.entries());
                                                                                                                                                                            
                                                                                                                                                                                        // Aqui você normalmente faria uma requisição AJAX
                                                                                                                                                                                                    console.log('Dados do formulário:', formValues);
                                                                                                                                                                                                                
                                                                                                                                                                                                                            // Feedback para o usuário
                                                                                                                                                                                                                                        alert('Mensagem enviada com sucesso! Entraremos em contato em breve.');
                                                                                                                                                                                                                                                    contactForm.reset();
                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                        // Scroll suave para links internos
                                                                                                                                                                                                                                                                            document.querySelectorAll('a[href^="#"]').forEach(anchor => {
                                                                                                                                                                                                                                                                                    anchor.addEventListener('click', function(e) {
                                                                                                                                                                                                                                                                                                e.preventDefault();
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                        const targetId = this.getAttribute('href');
                                                                                                                                                                                                                                                                                                                                    if (targetId === '#') return;
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                            const targetElement = document.querySelector(targetId);
                                                                                                                                                                                                                                                                                                                                                                        if (targetElement) {
                                                                                                                                                                                                                                                                                                                                                                                        window.scrollTo({
                                                                                                                                                                                                                                                                                                                                                                                                            top: targetElement.offsetTop - 80, // Ajuste para o header fixo
                                                                                                                                                                                                                                                                                                                                                                                                                                behavior: 'smooth'
                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Animação de elementos ao scroll
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function animateOnScroll() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const elements = document.querySelectorAll('.service-card, .stat, .client-logo');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elements.forEach(element => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const elementPosition = element.getBoundingClientRect().top;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const screenPosition = window.innerHeight / 1.3;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (elementPosition < screenPosition) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            element.style.opacity = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            element.style.transform = 'translateY(0)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Inicializar estilos para animação
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const animatedElements = document.querySelectorAll('.service-card, .stat, .client-logo');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    animatedElements.forEach(element => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            element.style.opacity = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    element.style.transform = 'translateY(20px)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            element.style.transition = 'opacity 0.5s ease, transform 0.5s ease';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Verificar animação no carregamento e no scroll
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            window.addEventListener('load', animateOnScroll);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                window.addEventListener('scroll', animateOnScroll);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });